//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmppBot.GetParsedText
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depster
    {
        public int Id { get; set; }
        public string Given_Name { get; set; }
        public string Additional_Name { get; set; }
        public string Family_Name { get; set; }
        public string E_mail_Type { get; set; }
        public string E_mail_Value { get; set; }
        public string Phone_Type { get; set; }
        public string Phone_Value { get; set; }
        public string Organization_Name { get; set; }
    }
}
