//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmppBot.GetParsedText
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeptBotEntities : DbContext
    {
        public DeptBotEntities()
            : base("name=DeptBotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Depster> Depsters { get; set; }
    
        public virtual ObjectResult<SetNextRunTime_Result> SetNextRunTime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SetNextRunTime_Result>("SetNextRunTime");
        }
    }
}
