using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace XmppBot.GetParsedText
{
	public class Questions
	{
		public static Dictionary<string, QuestionType> QuestionList;
		public static Dictionary<string, string> ContactList;

		public Questions()
		{
			Questions.QuestionList = Questions.QuestionList ?? this.GetQuestionsList();
			Questions.ContactList = Questions.ContactList ?? this.GetContactssList();
		}

		private Dictionary<string, string> GetContactssList()
		{
			Dictionary<string, string> contactsList = new Dictionary<string, string>()
			{
				{"abhinav.jain@deptagency.com", "Abhinav Jain"},
                {"insights@afriendofmine.nl", "ABN Insights"},
                {"acquisio@expandonline.nl", "Acquisio Account"},
                {"adwords@afriendofmine.nl", "Ad Words"},
                {"a.ball@building-blocks.com", "Adam Ball"},
                {"a.holt@building-blocks.com", "Adam Holt"},
                {"admar.de.bruin@tamtam.nl", "Admar de Bruin"},
                {"administratie@seconddegree.nl", "Administratie Second Degree"},
                {"adriaan.bakker@deptagency.com", "Adriaan Bakker"},
                {"adrian@tamtam.nl", "Adrian Klingen"},
                {"afom.insights@afriendofmine.nl", "afom insights"},
                {"a.asghar@building-blocks.com", "Aishah Asghar"},
                {"aleksandra@afriendofmine.nl", "Aleksandra Gajda"},
                {"a.hall@building-blocks.com", "Alex Hall"},
                {"alexander@tamtam.nl", "Alexander van Noord"},
                {"ali.safdari@tamtam.nl", "Ali Safdari"},
                {"aljosja.jacobs@expandonline.nl", "Aljosja Jacobs"},
                {"aprinsen@expandonline.nl", "Amber Prinsen"},
                {"adujso@expandonline.nl", "Amela Dujso"},
                {"a.johnson@building-blocks.com", "Amelia Johnson"},
                {"a.sadler@building-blocks.com", "Amy Sadler"},
                {"ana.garza@afriendofmine.nl", "Ana Garza"},
                {"ana@afriendofmine.nl", "Ana Mendez"},
                {"analytics@building-blocks.com", "Analytics Account"},
                {"andrea@seconddegree.nl", "Andrea Schol"},
                {"a.blackledge@building-blocks.com", "Andrew Blackledge"},
                {"a.emmerson@building-blocks.com", "Andrew Emmerson"},
                {"a.iddon@building-blocks.com", "Andrew Iddon"},
                {"android@deptagency.com", "Android Dept"},
                {"android@tamtam.nl", "android Unknown"},
                {"android_test@tamtam.nl", "android_test Unknown"},
                {"a.butterworth@building-blocks.com", "Andy Butterworth"},
                {"a.todd@building-blocks.com", "Andy Todd"},
                {"anela.strujic@deptagency.com", "Anela Strujic"},
                {"anique.vanvelde@deptagency.com", "Anique van Velde"},
                {"ankem@tamtam.nl", "Anke Meels"},
                {"anne@tamtam.nl", "Anne van den Hoogen"},
                {"anne.veerman@expandonline.nl", "Anne Veerman"},
                {"annelouj@tamtam.nl", "Annelou Jansen"},
                {"annemarie@seconddegree.nl", "Annemarie Moerman"},
                {"anniekw@tamtam.nl", "Anniek van de Weerdhof"},
                {"anniek@expandonline.nl", "Anniek van de Weerdhof"},
                {"avanadrichem@expandonline.nl", "Anouk van Adrichem"},
                {"a.galati@building-blocks.com", "Anthony Galati"},
                {"apifeeds@building-blocks.com", "API Feeds"},
                {"mailarchive@building-blocks.com", "Archief | Building Blocks"},
                {"mailarchive@seconddegree.nl", "Archief | Second Degree"},
                {"archief@studiodumbar.com", "Archief | Studio Dumbar"},
                {"mailarchive@expandonline.nl", "Archief Expand Online"},
                {"mailarchive@deptagency.com", "Archive | Dept Agency"},
                {"arjanb@expandonline.nl", "Arjan Brand"},
                {"arjan@tamtam.nl", "Arjan Lugthart"},
                {"armand@tamtam.nl", "Armand Kruizinga"},
                {"averwoert@expandonline.nl", "Arne Verwoert"},
                {"arnout@tamtam.nl", "Arnout Cornelissen"},
                {"arthur@tamtam.nl", "Arthur Stobbelaar"},
                {"asa@tamtam.nl", "Asa Alvebrand"},
                {"ash@afriendofmine.nl", "Ash Colcott"},
                {"assistance@afriendofmine.nl", "Assistance A friend of mine"},
                {"astrid@tamtam.nl", "Astrid van Marion"},
                {"attachments@tamtam.nl", "Attachments Catch All"},
                {"banners@deptagency.com", "Banner Team"},
                {"barry@tamtam.nl", "Barry Borsboom"},
                {"barry.vandertas@deptagency.com", "Barry van der Tas"},
                {"bart@tamtam.nl", "Bart Manuel"},
                {"bart.poelstra@expandonline.nl", "Bart Poelstra"},
                {"bart.vanlunteren@expandonline.nl", "Bart van Lunteren"},
                {"bartv@tamtam.nl", "Bart Venderbosch"},
                {"bart@studiodumbar.com", "Bart Vollebregt"},
                {"bart.willemsen@tamtam.nl", "Bart Willemsen"},
                {"bas.brouwer@tamtam.nl", "Bas Brouwer"},
                {"bdeknegt@expandonline.nl", "Bas de Knegt"},
                {"bas.heijnis@afriendofmine.nl", "Bas Heijnis"},
                {"bas.van.der.heijden@tamtam.nl", "Bas van der Heijden"},
                {"bas@seconddegree.nl", "Bas van Kooij"},
                {"bdo@deptagency.com", "BDO Accountant"},
                {"bobt@tamtam.nl", "Bob Toorenaar"},
                {"bonne.deroos@tamtam.nl", "Bonne de Roos"},
                {"bonnie@seconddegree.nl", "Bonnie Choi"},
                {"bootcamp@deptagency.com", "boot camp"},
                {"bosse@studiodumbar.com", "Bosse Kemper"},
                {"boyd.vandongen@expandonline.nl", "Boyd van Dongen"},
                {"b.pennington@building-blocks.com", "Brad Pennington"},
                {"bramw@tamtam.nl", "Bram Willemse"},
                {"bram@tamtam.nl", "Bram Zeijlmans van Emmichoven"},
                {"bvankluijve@expandonline.nl", "Brenda van Kluijve"},
                {"brian.olson@tamtam.nl", "Brian Olson"},
                {"b.robinson@building-blocks.com", "Brian Robinson"},
                {"c.ashton@building-blocks.com", "Callum Ashton"},
                {"caspar.heijdendael@expandonline.nl", "Caspar Heydendael"},
                {"catelijne@tamtam.nl", "Catelijne Vil\\\\u00e9"},
                {"celine.kalfsbeek@tamtam.nl", "Celine Kalfsbeek"},
                {"cemy@tamtam.nl", "Cem Yildiz"},
                {"c.dando@building-blocks.com", "Chris Dando"},
                {"c.eccles@building-blocks.com", "Chris Eccles"},
                {"c.morgan@building-blocks.com", "Chris Morgan"},
                {"claudia.pronk@deptagency.com", "Claudia Pronk"},
                {"coen@tamtam.nl", "Coen Huijsmans"},
                {"c.lawrenson@building-blocks.com", "Craig Lawrenson"},
                {"cristian@tamtam.nl", "Cristian van Nispen"},
                {"curt@tamtam.nl", "Curt Hoyer"},
                {"daanh@tamtam.nl", "Daan Hoffman"},
                {"daan@studiodumbar.com", "Daan Rietbergen"},
                {"dschouman@expandonline.nl", "Daan Schouman"},
                {"daane@tamtam.nl", "Daan van den Eeden"},
                {"damiano@afriendofmine.nl", "Damiano Trimboli"},
                {"d.carr@building-blocks.com", "Dan Carr"},
                {"dani.vanrooij@expandonline.nl", "Dani van Rooij"},
                {"d.franco@building-blocks.com", "Daniel Franco"},
                {"daniel.hoffmann@expandonline.nl", "Daniel Hoffmann"},
                {"d.lane@building-blocks.com", "Daniel Lane"},
                {"d.paterson@building-blocks.com", "Daniel Paterson"},
                {"danielsw@tamtam.nl", "Dani\\\\u00ebl Swaab"},
                {"d.winters@building-blocks.com", "Daniel Winters"},
                {"daniellez@tamtam.nl", "Dani\\\\u00eblle van der Zwan"},
                {"danijel@tamtam.nl", "Danijel Bonacic"},
                {"danny.hoek@deptagency.com", "Danny Hoek"},
                {"daphne@tamtam.nl", "Daphne Smit"},
                {"darrell.poleon@tamtam.nl", "Darrell Poleon"},
                {"d.grant@building-blocks.com", "Dave Grant"},
                {"dave@afriendofmine.nl", "Dave Jelderda"},
                {"d.goldman@building-blocks.com", "David Goldman"},
                {"d.jones@building-blocks.com", "David Jones"},
                {"david.leonardi@deptagency.com", "David Leonardi"},
                {"delilah@studiodumbar.com", "Delilah Butler"},
                {"denis.tunovic@tamtam.nl", "Denis Tunovic"},
                {"dennis.milandt@tamtam.nl", "Dennis Milandt"},
                {"events@deptagency.com", "Dept Agency"},
                {"bot@deptagency.com", "Dept Bot"},
                {"college@deptagency.com", "Dept College"},
                {"reception@deptagency.com", "Dept reception"},
                {"salessupport@deptagency.com", "Dept Sales Support"},
                {"updates@deptagency.com", "Dept Updates"},
                {"dvisser@expandonline.nl", "Derek Visser"},
                {"design@building-blocks.com", "Design Team"},
                {"developer.social.apps@tamtam.nl", "Developer Social Apps"},
                {"development@expandonline.nl", "Development Expand"},
                {"diana.nguyen@tamtam.nl", "Diana Nguyen"},
                {"diede.intveld@tamtam.nl", "Diede in't Veld"},
                {"dimi@tamtam.nl", "Dimi Albers"},
                {"dionne.vanderbol@deptagency.com", "Dionne van der Bol"},
                {"drive@afriendofmine.nl", "Drive | a friend of mine"},
                {"drive@deptagency.com", "Drive | Dept"},
                {"drive@expandonline.nl", "Drive | Expand Online"},
                {"drive@seconddegree.nl", "Drive | Second Degree"},
                {"drive@studiodumbar.com", "Drive | Studio Dumbar"},
                {"duarte@tamtam.nl", "Duarte Nobrega"},
                {"dwayne.buurstede@tamtam.nl", "Dwayne Buurstede"},
                {"edwin.kortman@tamtam.nl", "Edwin Kortman"},
                {"eefjeko@tamtam.nl", "Eefje Koopman"},
                {"egencia@building-blocks.com", "Egencia Travel"},
                {"elaine@tamtam.nl", "Elaine Hogenboom"},
                {"e.smith@building-blocks.com", "Elaine Smith"},
                {"e.vogiatzi@building-blocks.com", "Eleni Vogiatzi"},
                {"eline.steijlen@expandonline.nl", "Eline Steijlen"},
                {"eliza@seconddegree.nl", "Eliza van der Laan"},
                {"elmar@tamtam.nl", "Elmar Kouwenhoven"},
                {"e.robinson@building-blocks.com", "Emma Robinson"},
                {"e.schmitt@building-blocks.com", "Eric Schmitt"},
                {"erik@studiodumbar.com", "Erik de Vlaam"},
                {"erik@tamtam.nl", "Erik Heemskerk"},
                {"butlins.errors@building-blocks.com", "Errors Butlins"},
                {"warner.errors@building-blocks.com", "Errors Warner"},
                {"ebossers@expandonline.nl", "Erwin Bossers"},
                {"esther.heeremans@deptagency.com", "Esther Heeremans"},
                {"e.heeremans@building-blocks.com", "Esther Heeremans"},
                {"eva@seconddegree.nl", "Eva van den Born"},
                {"expandonline@expandonline.nl", "expand online"},
                {"trainingen@expandonline.nl", "Expand Trainingen"},
                {"fabienne@studiodumbar.com", "Fabienne Lentes"},
                {"facebook@expandonline.nl", "Facebook Expand Online"},
                {"ferry@tamtam.nl", "Ferry den Dopper"},
                {"fripping@expandonline.nl", "Fieke Ripping"},
                {"finance@afriendofmine.nl", "Finance a friend of mine"},
                {"finance@expandonline.nl", "Finance Expand Online"},
                {"fos@tamtam.nl", "Finance OS"},
                {"finance@tamtam.nl", "finance_mailbox - Tam Tam"},
                {"fleur@afriendofmine.nl", "Fleur Corman"},
                {"floor@afriendofmine.nl", "Floor Nobels"},
                {"floraholland.support@tamtam.nl", "FloraHolland Support"},
                {"floris@seconddegree.nl", "Floris van Krimpen"},
                {"florisw@expandonline.nl", "Floris Wulffele"},
                {"fouad@afriendofmine.nl", "Fouad El Hamdaoui"},
                {"francescag@expandonline.nl", "Francesca Gianfiglio"},
                {"f.benitez@building-blocks.com", "Francisco Benitez"},
                {"frank@tamtam.nl", "Frank (no reply)"},
                {"frank@afriendofmine.nl", "Frank Ouwerkerk"},
                {"frank.schmid@tamtam.nl", "Frank Schmid"},
                {"frank.stolker@deptagency.com", "Frank Stolker"},
                {"frank.vanderaa@expandonline.nl", "Frank van der Aa"},
                {"frankh@tamtam.nl", "Frank van der Hammen"},
                {"franklins@tamtam.nl", "Franklin Schamhart"},
                {"fred@afriendofmine.nl", "Frederik Snijder"},
                {"frederike@afriendofmine.nl", "Frederike Schouten"},
                {"freek@seconddegree.nl", "Freek Staps"},
                {"friso.postuma@tamtam.nl", "Friso Postuma"},
                {"g.rosado@building-blocks.com", "Gabriel Rosado"},
                {"galya@studiodumbar.com", "Galina Kruzhilina"},
                {"gawein@tamtam.nl", "Gawein Heymans"},
                {"geert@tamtam.nl", "Geert Fokke"},
                {"geworka@tamtam.nl", "Gework Arakel"},
                {"gijs.edelbroek@deptagency.com", "Gijs Edelbroek"},
                {"g.edelbroek@building-blocks.com", "Gijs Edelbroek"},
                {"giliamv@tamtam.nl", "Giliam Verheide"},
                {"goldwyn.latuheru@tamtam.nl", "Goldwyn Latuheru"},
                {"googledrive@building-blocks.com", "Google Drive"},
                {"drive@tamtam.nl", "Google Drive"},
                {"greg.trahair@deptagency.com", "Greg Trahair"},
                {"gregory@tamtam.nl", "Gregory Bolkenstijn"},
                {"guilliano.vitalis@tamtam.nl", "Guilliano Vitalis"},
                {"g.pannu@building-blocks.com", "Gurminder Pannu"},
                {"hadrienb@expandonline.nl", "Hadrien Buret"},
                {"hannah@seconddegree.nl", "Hannah Tomasowa"},
                {"hanne@afriendofmine.nl", "Hanne Martens"},
                {"hbraamse@expandonline.nl", "Hanneke Braamse"},
                {"hans@afriendofmine.nl", "Hans Muelders"},
                {"htemolder@expandonline.nl", "Harm te Molder"},
                {"h.arif@building-blocks.com", "Haroon Arif"},
                {"h.sanders@building-blocks.com", "Harriet Sanders"},
                {"harry.van.der.valk@tamtam.nl", "Harry van der Valk"},
                {"hedwich.degroot@tamtam.nl", "Hedwich de Groot"},
                {"h.jakobsen@building-blocks.com", "Helle Jakobsen"},
                {"recruitment@afriendofmine.nl", "HR \\\\u0026 recruitment AFOM"},
                {"hr@tamtam.nl", "HR Department"},
                {"hr@expandonline.nl", "HR Expand Online"},
                {"hycinth@tamtam.nl", "Hycinth Brussee"},
                {"i.hussain@building-blocks.com", "Ibrar Hussain"},
                {"ibtissam.ibrahmi@deptagency.com", "Ibtissam Ibrahmi"},
                {"ict@deptagency.com", "ICT Deptagency"},
                {"ill@tamtam.nl", "Ill TamTam"},
                {"info@studiodumbar.com", "Info | Studio Dumbar"},
                {"info@expandonline.nl", "info Expand Online"},
                {"info@tamtam.nl", "Info TamTam"},
                {"info@unskippable.com", "Info Unskippable"},
                {"insights.abn@afriendofmine.nl", "Insights abn"}

			};
			return contactsList;
		}

		private Dictionary<string, QuestionType> GetQuestionsList()
		{
			Dictionary<string, QuestionType> questionsList = new Dictionary<string, QuestionType>()
			{
				{ "weather", QuestionType.Weather },
				{ "wather", QuestionType.Weather },
				{ "wether", QuestionType.Weather },
				{ "weathe", QuestionType.Weather },
				{ "weathr", QuestionType.Weather },
				{ "weer", QuestionType.Weather },
				{ "mortgage", QuestionType.MortgageInfo },
				{ "Mortgag", QuestionType.MortgageInfo },
				{ "lenen", QuestionType.MortgageInfo },
				{ "loan", QuestionType.MortgageInfo },
				{ "free", QuestionType.RoomQuery },
				{ "available", QuestionType.RoomQuery },
				{ "vacant", QuestionType.RoomQuery },
				{ "salary", QuestionType.MortgageCalculation },
				{ "salry", QuestionType.MortgageCalculation },
				{ "salay", QuestionType.MortgageCalculation },
				{ "salar", QuestionType.MortgageCalculation },
				{ "age", QuestionType.MortgageCalculation },
				{ "salaris", QuestionType.MortgageCalculation },
				{ "salris", QuestionType.MortgageCalculation },
				{ "salars", QuestionType.MortgageCalculation },
				{ "busy", QuestionType.FindIndividualQuery },
				{ "doing", QuestionType.FindIndividualQuery },
				{ "busy now", QuestionType.FindIndividualQuery },
				{ "doing now", QuestionType.FindIndividualQuery },
				{ "jira issue", QuestionType.JiraIssue },
				{ "jira issues", QuestionType.JiraIssue },
				{ "issue in jira", QuestionType.JiraIssue },
				{ "issues in jira", QuestionType.JiraIssue },
				{ "jiraissue", QuestionType.JiraIssue },
				{ "jiraissues", QuestionType.JiraIssue },
				{ "jira assigned", QuestionType.JiraIssue },
				{ "jira task", QuestionType.JiraIssue },
				{ "price compare", QuestionType.CommodityPrice },
				{ "price vergelijk", QuestionType.CommodityPrice },
				{ "prijs compare", QuestionType.CommodityPrice },
				{ "rpijs vergelijk", QuestionType.CommodityPrice },
				{ "compare price", QuestionType.CommodityPrice },
				{ "vergelijk price ", QuestionType.CommodityPrice },
				{ "compare prijs", QuestionType.CommodityPrice },
				{ "vergelijk prijs", QuestionType.CommodityPrice },
				{ "price ", QuestionType.CommodityPrice },
				{ "prijs", QuestionType.CommodityPrice },
				{ "cpmpare ", QuestionType.CommodityPrice },
				{ "vergelijk", QuestionType.CommodityPrice }
			};
			return questionsList;
		}
		public enum QuestionType
		{
			UnknownQuestionType,
			Weather,
			MortgageInfo,
			MortgageCalculation,
			RoomQuery,
			FindIndividualQuery,
			JiraIssue,
			CommodityPrice
		}
	}
}
